feat: 環境変数名の変更

diff --git a/scripts/bin/an b/scripts/bin/an
--- a/scripts/bin/an
+++ b/scripts/bin/an
@@ -1,7 +1,7 @@
 #!/bin/bash
 
-FUNCTION_PATH=${WORKSPACE_ROOT}/scripts/functions.sh
-UTILS_PATH=${WORKSPACE_ROOT}/scripts/utils.sh
+FUNCTION_PATH=$PRODUCT_DIR/scripts/functions.sh
+UTILS_PATH=$PRODUCT_DIR/scripts/utils.sh
 source ${FUNCTION_PATH}
 source ${UTILS_PATH}
 
@@ -9,14 +9,14 @@ source ${UTILS_PATH}
 
 log "Run" "$1 ${*:2}"
 
-cd ${WORKSPACE_ROOT}
+cd $PRODUCT_DIR
 
-if grep -e "^function _${1}.*{$" $FUNCTION_PATH &> /dev/null
+if grep -e "^function _$1.*{$" $FUNCTION_PATH &> /dev/null
 then
   COMMAND=${1:-help}
 else
   COMMAND=help
-  log "Error" "${1}: command no found"
+  log "Error" "$1: command no found"
 fi
 
-_${COMMAND}_ ${*:2} || (log "Error" "${COMMAND} command failed"; exit 1)
+_${COMMAND}_ ${*:2} || (log "Error" "$COMMAND command failed"; exit 1)
